.github/workflows/main.yml
include/libp2p/multi/multihash.hpp
src/multi/multihash.cpp
src/peer/peer_id.cpp
test/acceptance/p2p/muxer.cpp
test/libp2p/multi/multihash_test.cpp

Signed-off-by: Bogdan Vaneev <warchantua@gmail.com>

Add mac build & add ctest

---

include/libp2p/multi/content_identifier.hpp
include/libp2p/multi/content_identifier_codec.hpp
include/libp2p/multi/hash_type.hpp
include/libp2p/multi/multicodec_type.hpp
include/libp2p/multi/multihash.hpp
include/libp2p/multi/uvarint.hpp
src/multi/CMakeLists.txt
src/multi/content_identifier.cpp
src/multi/content_identifier_codec.cpp
src/multi/multihash.cpp
src/multi/uvarint.cpp
src/peer/peer_id.cpp
test/libp2p/multi/CMakeLists.txt
test/libp2p/multi/cid_test.cpp
test/libp2p/multi/multihash_test.cpp

**Description of the Change**
Introduce CID implementation, which is an multiformats primitive, used to address content.
**Benefits**
It is used in IPFS and some other modules.

Content Identifier

---

README.md
example/01-echo/libp2p_echo_client.cpp
include/libp2p/muxer/mplex/mplexed_connection.hpp
src/multi/content_identifier_codec.cpp
src/muxer/mplex/mplexed_connection.cpp

Add readme and fix all clang-tidy issues

Add readme

---

include/libp2p/crypto/crypto_provider/crypto_provider_impl.hpp
src/crypto/crypto_provider/crypto_provider_impl.cpp
test/libp2p/crypto/CMakeLists.txt
test/libp2p/crypto/key_generator_test.cpp

Signed-off-by: turuslan <turuslan.devbox@gmail.com>

FIL-59 ECDSA

---

.clang-tidy
.github/workflows/clang-tidy.yml
housekeeping/clang-tidy.sh
housekeeping/codecov.sh
housekeeping/filter_compile_commands.py

add clang-tidy as GitHub action

add clang tidy gh

---

src/crypto/ed25519_provider/ed25519_provider_impl.cpp
test/libp2p/crypto/key_generator_test.cpp

The test is added.
A little drawback in implementation is fixed.

Add Ed25519 basic test and fix sign/verify implementation

---

include/libp2p/multi/hash_type.hpp
include/libp2p/multi/multicodec_type.hpp
test/libp2p/multi/cid_test.cpp

Add missing enum values required for filecoin

More multiformat enum values

---

.github/workflows/ci.yml

Fix apt-get update failing.
https://github.community/t5/GitHub-Actions/ubuntu-latest-Apt-repository-list-issues/td-p/41122

Fix apt-get update

---

include/libp2p/multi/content_identifier.hpp
include/libp2p/multi/multihash.hpp
src/multi/content_identifier.cpp
src/multi/multihash.cpp
test/libp2p/multi/cid_test.cpp
test/libp2p/multi/multihash_test.cpp

Signed-off-by: Alexey-N-Chernyshov <alexey.n.chernyshov@gmail.com>

CID less operator

---

include/libp2p/multi/uvarint.hpp
src/multi/uvarint.cpp

Signed-off-by: Alexey-N-Chernyshov <alexey.n.chernyshov@gmail.com>

add < operator to UVarint

---

include/libp2p/multi/multibase_codec.hpp
src/multi/multibase_codec/multibase_codec_impl.cpp
test/libp2p/multi/cid_test.cpp
test/libp2p/multi/multibase_codec_test.cpp

Signed-off-by: artyom-yurin <artem_yrin@mail.ru>

Fixed Base58 encode prefix

---

src/multi/multibase_codec/codecs/base32.cpp

Signed-off-by: artyom-yurin <artem_yrin@mail.ru>

Added copyright header

---

CMakeLists.txt
cmake/Hunter/config.cmake
cmake/Hunter/init.cmake
cmake/dependencies.cmake

Changed cmake-files for using internal fork of Hunter package manager.
Added version of project (setup 0.0.1).

Change cmake-files for using internal fork of Hunter package manager

---

include/libp2p/multi/converters/converter_utils.hpp
include/libp2p/multi/multiaddress.hpp
src/multi/converters/converter_utils.cpp
src/multi/multiaddress.cpp
src/protocol/identify/identify_msg_processor.cpp
test/libp2p/protocol/identify_test.cpp

Signed-off-by: iceseer <iceseer@gmail.com>
Fixes remote address and listen addresses fields in ```Identify``` message.

protocol fields serialization fix

---

include/libp2p/basic/message_read_writer.hpp
src/basic/message_read_writer_uvarint.cpp

Signed-off-by: iceseer <iceseer@gmail.com>

zero-data fix

---

include/libp2p/host/basic_host/basic_host.hpp
include/libp2p/host/host.hpp
src/host/basic_host/basic_host.cpp
test/mock/libp2p/host/host_mock.hpp

On new connection event notification
Signed-off-by: iceseer <iceseer@gmail.com>

on new connection event subscription

---

example/01-echo/libp2p_echo_client.cpp
example/01-echo/libp2p_echo_server.cpp
example/03-gossip/gossip_chat_example.cpp
example/04-dnstxt/ares_resolver.cpp

Fix examples

---

cmake/Hunter/config.cmake
cmake/Hunter/init.cmake
test/testutil/prepare_loggers.hpp

Signed-off-by: Dmitriy Khaustov aka xDimon <khaustov.dm@gmail.com>

Sync logging with updated soralog

---

src/protocol/kademlia/CMakeLists.txt
src/protocol/kademlia/impl/CMakeLists.txt

Signed-off-by: ortyomka <iurin.art@gmail.com>

Fix kademlia cmake

---

src/log/configurator.cpp
test/testutil/prepare_loggers.hpp

PR adds config of logging system for using in unit tests

Configure logger for testutil

---

cmake/Hunter/init.cmake

Use updated Hunter with soralog 0.0.5

---

include/libp2p/basic/scheduler.hpp
include/libp2p/basic/scheduler/asio_scheduler_backend.hpp
include/libp2p/basic/scheduler/scheduler_impl.hpp
include/libp2p/outcome/outcome.hpp
src/basic/CMakeLists.txt
src/basic/scheduler.cpp
src/basic/scheduler/asio_scheduler_backend.cpp
src/basic/scheduler/scheduler_impl.cpp
test/acceptance/p2p/host/peer/test_peer.hpp
test/libp2p/basic/CMakeLists.txt
test/libp2p/basic/scheduler_test.cpp
test/testutil/CMakeLists.txt
test/testutil/async/CMakeLists.txt
test/testutil/async/clock.hpp
test/testutil/async/impl/clock_impl.cpp
test/testutil/async/impl/clock_impl.hpp
test/testutil/async/manual_scheduler_backend.cpp
test/testutil/async/manual_scheduler_backend.hpp
test/testutil/outcome.hpp

New scheduler fixes protocol/common/scheduler

New Scheduler

---

include/libp2p/common/literals.hpp
src/common/literals.cpp
test/acceptance/p2p/muxer.cpp

Signed-off-by: ortyomka <iurin.art@gmail.com>

Fix size_t problem

---

src/connection/loopback_stream.cpp

Revert "Allow blocks finalization for Kagome project"

---

cmake/Hunter/config.cmake
cmake/Hunter/init.cmake
src/protocol_muxer/multiselect.cpp

Fixes using SL_TRACE in some case

Fix trace log level

---

include/libp2p/network/connection_manager.hpp
include/libp2p/network/listener_manager.hpp
include/libp2p/network/router.hpp
include/libp2p/peer/identity_manager.hpp
include/libp2p/protocol/kademlia/impl/content_routing_table.hpp
include/libp2p/protocol/kademlia/impl/peer_routing_table.hpp
include/libp2p/protocol/ping/ping_client_session.hpp
src/host/basic_host/basic_host.cpp
src/network/impl/connection_manager_impl.cpp
src/protocol/identify/identify.cpp
src/protocol/identify/identify_delta.cpp
src/protocol/identify/identify_push.cpp
src/protocol/kademlia/impl/content_routing_table_impl.cpp
src/protocol/kademlia/impl/kademlia_impl.cpp
src/protocol/kademlia/impl/peer_routing_table_impl.cpp
src/protocol/ping/ping_client_session.cpp
test/libp2p/protocol/identify_delta_test.cpp
test/libp2p/protocol/identify_test.cpp
test/libp2p/protocol/kademlia/content_routing_table_test.cpp
test/libp2p/protocol/kademlia/peer_routing_table_test.cpp
test/libp2p/protocol/ping_test.cpp

This request fixes misresolving 'event' namespace within external project in some cases.

Reorganize 'event' namespaces

---

cmake/Hunter/init.cmake
cmake/dependencies.cmake
cmake/functions.cmake

Updated Hunter reference for both x64 and arm64 (M1) support on MasOS

Updated Hunter version for M1 support

---

include/libp2p/multi/multiaddress_protocol_list.hpp
src/multi/converters/converter_utils.cpp
test/libp2p/multi/multiaddress_test.cpp

Let x-parity-ws/wss multiaddrs to be constructed

---

include/libp2p/protocol/kademlia/impl/put_value_executor.hpp
src/protocol/kademlia/impl/kademlia_impl.cpp
src/protocol/kademlia/impl/put_value_executor.cpp

- Add check that key not empty in `FindNode` request
- Add response in `PutValue` request
- Add check that request is proceed in `PutValue`

Fix Kademlia Protocol

---

example/02-kademlia/rendezvous_chat.cpp
include/libp2p/protocol/kademlia/content_id.hpp
include/libp2p/protocol/kademlia/impl/put_value_executor.hpp
include/libp2p/protocol/kademlia/message.hpp
include/libp2p/protocol/kademlia/node_id.hpp
src/protocol/kademlia/impl/CMakeLists.txt
src/protocol/kademlia/impl/content_id.cpp
src/protocol/kademlia/impl/find_providers_executor.cpp
src/protocol/kademlia/impl/get_value_executor.cpp
src/protocol/kademlia/impl/kademlia_impl.cpp
src/protocol/kademlia/impl/put_value_executor.cpp
src/protocol/kademlia/message.cpp
test/libp2p/protocol/kademlia/content_routing_table_test.cpp

- Kademlia key is arbitrary bytes, so remove format checks
- fix `PutValue` https://github.com/libp2p/cpp-libp2p/pull/190

Fix kademlia

---

CMakeLists.txt
cmake/Hunter/init.cmake
include/libp2p/log/sublogger.hpp
include/libp2p/outcome/outcome.hpp
test/libp2p/muxer/muxers_and_streams_test.cpp
test/libp2p/protocol/gossip/CMakeLists.txt

fix: using soralog
feature: formatter for outcome
fix: muxer and streams test
update: hunter

Fixes for C++20 support

---

include/libp2p/protocol/kademlia/common.hpp
include/libp2p/protocol/kademlia/config.hpp
include/libp2p/protocol/kademlia/impl/kademlia_impl.hpp
src/protocol/kademlia/impl/add_provider_executor.cpp
src/protocol/kademlia/impl/find_peer_executor.cpp
src/protocol/kademlia/impl/find_providers_executor.cpp
src/protocol/kademlia/impl/get_value_executor.cpp
src/protocol/kademlia/impl/kademlia_impl.cpp
src/protocol/kademlia/impl/put_value_executor.cpp

- https://github.com/paritytech/substrate/pull/12545

kademlia multiple protocols

---

include/libp2p/common/final_action.hpp

- moved optional was not reset

fix final action

---

cmake/Hunter/init.cmake
include/libp2p/protocol/kademlia/config.hpp
include/libp2p/protocol/kademlia/impl/kademlia_impl.hpp
include/libp2p/protocol/kademlia/peer_routing.hpp
src/protocol/kademlia/impl/kademlia_impl.cpp

- expose random walk method for manual strategies [(exponential, min peer count, ...)](https://github.com/paritytech/polkadot-sdk/blob/29c8130bab0ed8216f48e47a78c602e7f0c5c1f2/substrate/client/network/src/discovery.rs#L702-L724)

kademlia random walk method

---

.github/workflows/ci.yml
include/libp2p/injector/host_injector.hpp
include/libp2p/injector/kademlia_injector.hpp
include/libp2p/injector/network_injector.hpp
test/libp2p/muxer/muxers_and_streams_test.cpp

- remove unnecessary `template`

fix injector compiler error

---

CMakeLists.txt

Fix PACKAGE_MANAGER condition in CMakeLists.txt
Fixes #308

Fix PACKAGE_MANAGER validation in CMakeLists.txt
