libp2p/cpp-libp2p

cmake/functions.cmake
src/crypto/key_marshaller/key_marshaller_impl.cpp
src/protocol/identify/identify_delta.cpp
src/protocol/identify/identify_msg_processor.cpp
src/security/plaintext/exchange_message_marshaller_impl.cpp
src/security/plaintext/protobuf/CMakeLists.txt
src/security/plaintext/protobuf/plaintext.proto
test/libp2p/protocol/identify_delta_test.cpp
test/libp2p/protocol/identify_test.cpp
test/libp2p/security/plaintext_exchange_message_marshaller_test.cpp

Changed protobuf generation paths.
Each generated pair of proto files (header and source) now placed into following directory:
${CMAKE_BINARY_DIR}/pb/${PROTO_LIBRARY_NAME}/generated/${PROTO_FILE_DIR_RELATIVE_TO_SRC}
When you need to include generated file you should write following include:
```#include <generated/${PROTO_FILE_DIR_RELATIVE_TO_SRC}/${PROTO_FILE_NAME}.proto```
for example
```#include <generated/security/plaintext/protobuf/plaintext.pb.h>```

fix generation paths

---

.gitmodules
CMakeLists.txt
cmake/Hunter/config.cmake
cmake/boost_di.cmake
cmake/dependencies.cmake
cmake/hat-trie.cmake
example/01-echo/CMakeLists.txt
src/common/CMakeLists.txt
src/common/logger.cpp
src/network/impl/CMakeLists.txt
test/acceptance/p2p/host/host_integration_test.cpp
test/acceptance/p2p/host/peer/CMakeLists.txt
test/deps/CMakeLists.txt
test/libp2p/injector/CMakeLists.txt
test/libp2p/security/CMakeLists.txt

Remove dependencies deps checkout them as external projects using ExternalProject_Add cmake method.
The point is that when libp2p is being downloaded in Kagome, submodules are not checked out. 
Adding them as external project occurred the only way to get them in this case.
Boost di, spdlog, tsl hat-trie were removed.

remove git submodules deps

---

include/libp2p/crypto/key_generator/key_generator_impl.hpp
src/crypto/key_generator/key_generator_impl.cpp

Method was commented out in incorrect way, so the library couldn't compile in release mode.
I commented it out fully.

comment out gen rsa method

---

include/libp2p/outcome/outcome.hpp
src/protocol_muxer/multiselect/message_manager.cpp
test/deps/outcome_test.cpp
test/libp2p/crypto/marshaller_test.cpp
test/libp2p/multi/cid_test.cpp
test/libp2p/muxer/yamux/yamux_integration_test.cpp
test/libp2p/protocol_muxer/multiselect_test.cpp
test/libp2p/transport/tcp/tcp_integration_test.cpp
test/libp2p/transport/upgrader_test.cpp

Libp2p's outcome::result interferes with Kagome's outcome::result definitions.
Need to hide it into namespace.

hide outcome::result into libp2p namespace

---

cmake/Hunter/config.cmake

spdlog version wasn't bound to a tag, but to a branch.
each time a new commit appeared, hash was changed.
this change makes it stable.

fix spdlog config

---

src/CMakeLists.txt

p2p target of libp2p should contain p2p_default_host as well as p2p_default_network, for now host his missing. 
This fix adds p2p_default_host to p2p target.

add p2p_default_host to p2p

---

cmake/boost_di.cmake
cmake/hat-trie.cmake

di and hat trie don't need build step since they are header only.
test step is not required.

remove build and test steps for di and hat-trie

---

include/libp2p/crypto/crypto_provider.hpp
include/libp2p/crypto/crypto_provider/crypto_provider_impl.hpp
include/libp2p/crypto/error.hpp
include/libp2p/crypto/key_validator/key_validator_impl.hpp
include/libp2p/injector/network_injector.hpp
include/libp2p/network/default_network.hpp
include/libp2p/peer/impl/identity_manager_impl.hpp
src/crypto/CMakeLists.txt
src/crypto/crypto_provider/CMakeLists.txt
src/crypto/crypto_provider/crypto_provider_impl.cpp
src/crypto/error.cpp
src/crypto/key_marshaller/key_marshaller_impl.cpp
src/crypto/key_validator/CMakeLists.txt
src/crypto/key_validator/key_validator_impl.cpp
src/network/CMakeLists.txt
test/acceptance/p2p/host/peer/test_peer.cpp
test/acceptance/p2p/host/peer/test_peer.hpp
test/libp2p/crypto/CMakeLists.txt
test/libp2p/crypto/key_generator_test.cpp
test/libp2p/crypto/key_validator_test.cpp
test/libp2p/peer/CMakeLists.txt
test/libp2p/security/CMakeLists.txt

Add `sign` and `verify` methods required by private/public key cryptography to interfaces.
And change the meaning of KeyGenerator to CryptoProvider.

Transform KeyGenerator to CryptoProvider

---

include/libp2p/common/literals.hpp
include/libp2p/common/types.hpp
include/libp2p/crypto/common_functions.hpp
include/libp2p/crypto/crypto_provider/crypto_provider_impl.hpp
include/libp2p/crypto/ed25519_provider.hpp
include/libp2p/crypto/ed25519_provider/ed25519_provider_impl.hpp
include/libp2p/crypto/sha/sha512.hpp
include/libp2p/injector/network_injector.hpp
src/common/literals.cpp
src/crypto/CMakeLists.txt
src/crypto/common_functions.cpp
src/crypto/crypto_provider/CMakeLists.txt
src/crypto/crypto_provider/crypto_provider_impl.cpp
src/crypto/ed25519_provider/CMakeLists.txt
src/crypto/ed25519_provider/ed25519_provider_impl.cpp
src/crypto/sha/CMakeLists.txt
src/crypto/sha/sha256.cpp
src/crypto/sha/sha512.cpp
test/acceptance/p2p/host/peer/test_peer.cpp
test/acceptance/p2p/host/peer/test_peer.hpp
test/libp2p/crypto/key_generator_test.cpp
test/libp2p/crypto/key_validator_test.cpp

Introduces ed25519 provider as an independent component from libp2p CryptoProvider(ex-KeyGenerator), which will be used by the CryptoProvider and can be used by other projects where libp2p is just a dependency.
Ed25519Provider operates with byte sequences.
As a side effect, - SHA512 is also implemented.
No tests.

Implement Ed25519 crypto provider

---

cmake/Hunter/config.cmake

Signed-off-by: Yura Zarudniy <zarudniy@soramitsu.co.jp>
Use the same (gcc9.2-friendly) version of GTest as in kagome.

use gcc9.2-friendly version of GTest

---

.github/workflows/clang-tidy.yml

Signed-off-by: Yura Zarudniy <zarudniy@soramitsu.co.jp>
Clang tidy cannot find protobuf generated files, need to build the `generated` target before starting checks.
Added build step for `generated` target.

Fix clang tidy concern about generated files

---

.github/workflows/ci.yml

Update github pipeline macos
```The macOS virtual environment has been updated to Catalina (v10.15). Starting January 15th, jobs that include the line 'runs-on: macOS-10.14' will fail to run and return a failed check suite. Please update your workflow and change the line 'runs-on: macOS-10.14' to 'runs-on: macOS-latest'.```
Macos pipeline will continue working
Macos pipeline will stop working

Update github pipeline macos

---

include/libp2p/multi/content_identifier.hpp
include/libp2p/multi/content_identifier_codec.hpp
src/multi/CMakeLists.txt
src/multi/content_identifier.cpp
src/multi/content_identifier_codec.cpp
test/libp2p/multi/cid_test.cpp

Convert CID to string, e.g. `QmYTYMTdkVyB8we45bdXfZuDu5vCjRVX8QNTFLhC7K8C7t`
This implementation supports only **CID V0**, which always use `Base58` multibase encoding.

Convert CID to string representation

---

include/libp2p/multi/multihash.hpp
src/multi/multihash.cpp

Multihash has a serious issue. 
It contains as a member a gsl::span<> pointing to another member.
When another class A has multihash member, assigning its instance is risky.
If you create a temp instance, assign it to a permanent variable, the span is copied,  and then after destroying temp instance, the span starts to paint to invalid memory.
Multihash doesn't have a copy constructor, and it cannot be specified easily (I tried, but it broke some other things). 
I suppose we should get rid of keeping span as member, creating it when required, since it is a lightweight operation.

Fix multihash

---

include/libp2p/security/plaintext/exchange_message_marshaller.hpp
include/libp2p/security/plaintext/exchange_message_marshaller_impl.hpp
include/libp2p/security/plaintext/plaintext.hpp
include/libp2p/security/secio/exchange_message_marshaller.hpp
src/security/plaintext/CMakeLists.txt
src/security/plaintext/exchange_message_marshaller_impl.cpp
src/security/plaintext/plaintext.cpp
test/libp2p/security/plaintext_adaptor_test.cpp
test/mock/libp2p/security/exchange_message_marshaller_mock.hpp

Plaintext protocol was using wrong typed frames length prefixes.
Now it uses UVarInt length prefixes as it is defined in the [specification](https://github.com/libp2p/specs/tree/master/plaintext#message-framing).
`host_integration_test` and full-featured tests via `libp2p/example/01-echo/README.md`

Fix Plaintext security protocol

---

CMakeLists.txt
cmake/install.cmake

Mocks can be used in other projects to test libp2p-related code.

Export mock headers

---

src/crypto/crypto_provider/crypto_provider_impl.cpp
src/crypto/rsa_provider/rsa_provider_impl.cpp
src/protocol/kademlia/impl/kad_impl.cpp

Current build failed due to uninitialized local variables with 3 files. The build flagged these warnings as errors. A simple change fixed the issue and allowed the build to complete.

Fixed build issues with uninitialized local variables.

---

include/libp2p/transport/tcp/tcp_connection.hpp
include/libp2p/transport/tcp/tcp_util.hpp
src/transport/tcp/tcp_connection.cpp
src/transport/tcp/tcp_transport.cpp

Current PR introduces handling of multiaddresses containing dns-address. So that we can handle addresses like `/dns4/p2p.cc3-0.kusama.network/tcp/30100/p2p/QmeCit3Nif4VfNqrEJsdYHZGcKzRCnZvGxg6hha1iNj4mk`
Run libp2p server: 
`./libp2p_echo_server -insecure`
Run libp2p client:
`./libp2p_echo_client /dns4/localhost/tcp/40010/ipfs/12D3KooWEgUjBV5FJAuBSoNMRYFRHjV7PjZwRQ7b43EKX9g7D6xV`

Add proper dns-resolving

---

cmake/Hunter/init.cmake

Boost version 1.72.0-p0 from Hunter had an issue compiling with the Mac Os's Command line tools version 11.4.
Original hunter has the fix represented by the boost version 1.72.0-p1. Current PR bumps hunter to the version containing this boost version.
Therefore an issue compiling boost on the latest Mac OS should be resolved.
Pull request introducing latest boost version to our hunter: https://github.com/soramitsu/soramitsu-hunter/pull/5

Bump hunter version

---

.github/workflows/ci.yml
.github/workflows/clang-tidy.yml
CMakeLists.txt
housekeeping/clang-patch/apply.sh
housekeeping/clang-patch/clang-patch.c
include/libp2p/protocol/identify/identify.hpp
include/libp2p/protocol/identify/identify_msg_processor.hpp
src/peer/address_repository/inmem_address_repository.cpp
src/protocol/identify/identify.cpp
src/protocol/identify/identify_msg_processor.cpp

a small patch needed by fuhon:
1) new event (identify message received from peer)
2) address repository fix (event related)
3) identify message processor fix (allows to add addresses for previously unknown peer)

identify protocol signals

---

include/libp2p/muxer/mplex/mplex_stream.hpp
include/libp2p/muxer/yamux/yamux_stream.hpp
src/muxer/mplex/mplex_stream.cpp
src/muxer/yamux/yamux_stream.cpp

Using gsl::span in write queue in streams might be dangerous, as span does not store collection itself, but rather stores only pointer and size of the collection

Use vector in write queue

---

src/multi/multiaddress.cpp
test/libp2p/multi/multiaddress_test.cpp

Parsing in multiaddr is buggy. 
Example. Consider multiaddr `/dns4/p2p.cc3-0.kusama.network/tcp/30100/p2p/12D3KooWDgtynm4S9M3m6ZZhXYu2RrWKdvkCSScc25xKDVSg1Sjd`
GetPeerId on that multiaddr returns `tcp`, because it returns first word after word containing /p2p. However p2p is part of dns address. Current PR fixes that

Fix handling addresses starting from p2p

---

include/libp2p/multi/hash_type.hpp
include/libp2p/multi/multicodec_type.hpp

Added codecs:
- Sealed Filecoin commitment
- Unsealed Filecoin commitment
Added hashes:
- sha2 256 trunc254 padded
- poseidon bls12 381 a1 fc1

Filecoin codec and hash types

---

CMakeLists.txt
cmake/dependencies.cmake
cmake/functions.cmake
src/common/literals.cpp
src/muxer/yamux/yamux_frame.cpp

This PR contains a set of fixes and improvements to the build system to allow for cross-compiling, and then applies several code fixes needed for newer GCC versions.
The PR is organized as follows:
1. Improvements needed for cross-compiling
2. Build fixes
Commits:
- [CMake: Expose CMake options to includes](https://github.com/eigendude/libp2p/commit/cross-compile~5)
- [CMake: Exclude test dependencies when building tests](https://github.com/eigendude/libp2p/commit/cross-compile~4)
- [CMake: Allow build system to provide protobuf compiler](https://github.com/eigendude/libp2p/commit/cross-compile~3)
These changes enable more control over the build process when embedding in another build system.
CMake is controlled by user variables; the first one we need is `-DHUNTER_ENABLED=OFF` so that we …

Cross compiling fixes and improvements

---

src/network/impl/dialer_impl.cpp
test/libp2p/network/dialer_test.cpp

Addresses #96 
Initial behavior: in the best case, the dialer did a single attempt to connect to the peer using its first available address.
Corrected behavior: the dialer enumerates and tries all the supplied peer's addresses while trying to connect.
Also added a test:
```
ctest -R dialer_test --output-on-failure
```
The test will not pass in the current master branch without the fix.

Fix Dialing to Peers (allow use all peers' addresses)

---

.github/workflows/ci.yml
.github/workflows/coverage.yml
.gitignore
CMakeLists.txt
cmake/3rdparty/CodeCoverage.cmake
cmake/coverage.cmake
cmake/functions.cmake
codecov.yml

The PR turns on a separate target within Github Actions for composing coverage reports and submitting them to codecov.io.
Codecov.io bot is going to comment on all PRs to the master branch which are to be merged later on.
It is silent at that particular PR due to the absence of a baseline coverage report from the master branch, since this PR is not yet merged.
The latest version of `CodeCoverage.cmake` is took from [here](https://github.com/bilke/cmake-modules/blob/master/CodeCoverage.cmake).

Enable Code Coverage

---

include/libp2p/log/configurator.hpp

Logging system configurator has two ctors: default and second one with a single argument (yaml-content of config). At injection second one is called with empty string, what gets wrong behavior, although expected first of them. Second one is used only for overriden config.
This PR force to use default ctor of logger configurator at dependency injection.

Fix default logger configurator at injection

---

include/libp2p/connection/capable_connection.hpp
include/libp2p/host/basic_host/basic_host.hpp
include/libp2p/host/host.hpp
include/libp2p/muxer/mplex/mplexed_connection.hpp
include/libp2p/muxer/yamux/yamuxed_connection.hpp
include/libp2p/network/dialer.hpp
include/libp2p/network/impl/dialer_impl.hpp
src/host/basic_host/basic_host.cpp
src/muxer/mplex/mplexed_connection.cpp
src/muxer/yamux/yamuxed_connection.cpp
src/network/impl/dialer_impl.cpp
test/mock/libp2p/connection/capable_connection_mock.hpp
test/mock/libp2p/host/host_mock.hpp
test/mock/libp2p/network/dialer_mock.hpp

This resolves interop issues with some other libp2p implementations, which don't send ACK on inbound stream until they see data

Outbound streams optimistic creation

---

src/protocol/gossip/impl/peer_set.cpp

/dev/urandom was opened every time when where's no need in such RNG

avoid heavy usage of hardware RNG for non-cryptographic task

---

include/libp2p/network/impl/dialer_impl.hpp
src/network/impl/dialer_impl.cpp
test/acceptance/p2p/host/peer/test_peer.cpp
test/libp2p/network/CMakeLists.txt
test/libp2p/network/dialer_test.cpp

Dialer component is not reentrant. 
This prevents higher level protocol implementation from potential bugs and allows for more clear design

Non-reentant dialer component

---

cmake/Hunter/config.cmake
example/01-echo/libp2p_echo_client.cpp
example/01-echo/libp2p_echo_server.cpp
example/02-kademlia/rendezvous_chat.cpp
example/03-gossip/gossip_chat_example.cpp
example/03-gossip/utility.cpp
example/04-dnstxt/ares_resolver.cpp
include/libp2p/log/logger.hpp
src/basic/scheduler/asio_scheduler_backend.cpp
src/log/configurator.cpp
src/log/logger.cpp
test/testutil/prepare_loggers.hpp

Deprecate star-marked default group. PR provides explicitly defined default group (new soralog feature).
Signed-off-by: Dmitriy Khaustov aka xDimon <khaustov.dm@gmail.com>

Provide default logger group explicitly

---

example/03-gossip/gossip_chat_example.cpp
include/libp2p/log/sublogger.hpp
include/libp2p/muxer/yamux/yamux_reading_state.hpp
include/libp2p/muxer/yamux/yamuxed_connection.hpp
include/libp2p/peer/address_repository/inmem_address_repository.hpp
include/libp2p/protocol/gossip/gossip.hpp
src/basic/scheduler/scheduler_impl.cpp
src/muxer/yamux/yamux_reading_state.cpp
src/muxer/yamux/yamuxed_connection.cpp
src/peer/address_repository/inmem_address_repository.cpp
src/protocol/gossip/impl/common.hpp
src/protocol/gossip/impl/connectivity.cpp
src/protocol/gossip/impl/connectivity.hpp
src/protocol/gossip/impl/gossip_core.cpp
src/protocol/gossip/impl/gossip_core.hpp
src/protocol/gossip/impl/message_builder.cpp
src/protocol/gossip/impl/message_builder.hpp
src/protocol/gossip/impl/message_cache.cpp
src/protocol/gossip/impl/peer_context.hpp
src/protocol/gossip/impl/remote_subscriptions.cpp
src/protocol/gossip/impl/remote_subscriptions.hpp
src/protocol/gossip/impl/stream.cpp
src/protocol/gossip/impl/stream.hpp
src/protocol/gossip/impl/topic_subscriptions.cpp
test/libp2p/protocol/gossip/gossip_structures_test.cpp

Removing non actual peer information from gossip instances.
This self-cleanup is needed because some nodes use ephemeral peer ids

Gossip self cleanup

---

src/connection/loopback_stream.cpp

The fix brings back immediate callback invocation for the case when read or write operation occurs on a loopback stream.
Addresses the issue https://github.com/soramitsu/kagome/issues/710

Allow blocks finalization for Kagome project

---

include/libp2p/basic/varint_reader.hpp
include/libp2p/protocol/kademlia/impl/session.hpp
src/basic/message_read_writer_error.cpp
src/basic/message_read_writer_uvarint.cpp
src/basic/varint_reader.cpp
src/muxer/mplex/mplex_frame.cpp
src/protocol/gossip/impl/stream.cpp
src/protocol/gossip/impl/stream.hpp
src/protocol/kademlia/impl/session.cpp
test/mock/libp2p/basic/readwritecloser_mock.hpp

An error may happen about the network stream. Previously the error was silently substituted with the generic varint error. Now the actual error will be propagated to the calling code.

Let varint reader propagate the error

---

.github/workflows/ci.yml

Old github token to upload to [hunter binary cache](https://github.com/soramitsu/hunter-binary-cache) was expired, which causes problems on ci. To fix that we can remove tokens, which should disable upload

Remove hunter upload

---

include/libp2p/multi/multihash.hpp
include/libp2p/protocol/kademlia/impl/peer_routing_table_impl.hpp
src/multi/CMakeLists.txt
src/multi/multihash.cpp
src/protocol/kademlia/impl/peer_routing_table_impl.cpp

Fixed #146 
Multihash has immutable shared_ptr inside, including precalculated std::hash, allows for performance while copying, sharing, using as key in containers
UVarint stuff in Multihash creation changed to impl with no dynamic allocations
Kademlia's PeerRoutingTable fixed (bugs were detected while applying p.1)

multihash-and-fixes - Updated

---

src/log/CMakeLists.txt

This remove the unnecessary dependency on yaml-cpp, as it is already declared as an INTERFACE dependency of `soralog::configurator_yaml` in the CMake package config of soralog.

p2p_logger: remove already propagated dependency on yaml-cpp

---

test/libp2p/injector/CMakeLists.txt

Because `p2p_cares` is not part of `p2p_default_network`, but used in the network injector, testsuite compilation currently fails for me with:
```
In file included from /build/source/include/libp2p/network/impl/dnsaddr_resolver_impl.hpp:15,
from /build/source/include/libp2p/injector/network_injector.hpp:26,
from /build/source/test/libp2p/injector/network_injector_test.cpp:6:
/build/source/include/libp2p/network/cares/cares.hpp:17:10: fatal error: ares.h: No such file or directory
17 | #include <ares.h>
|          ^~~~~~~~
```
This PR fixes the issue for me.

tests: add missing p2p_cares dependency to network injector test

---

src/protocol/gossip/impl/connectivity.cpp
src/protocol/gossip/impl/stream.hpp

ASAN found 'heap-use-after-free' in gossip ([link](https://pastebin.com/uBDG1dK8)).
There is circular dependency in `Stream` and `PeerContext`.
`Stream` is passed as a weak pointer and is not locked [here](https://github.com/libp2p/cpp-libp2p/blob/7c9d83bf0760a5f653d86ddbb00645414c61d4fc/src/protocol/gossip/impl/connectivity.cpp#L54) and `PeerContext` is passed as a const ref [here](https://github.com/libp2p/cpp-libp2p/blob/7c9d83bf0760a5f653d86ddbb00645414c61d4fc/src/protocol/gossip/impl/connectivity.cpp#L53).
So, after shared pointer to `Stream` is [reset](https://github.com/libp2p/cpp-libp2p/blob/7c9d83bf0760a5f653d86ddbb00645414c61d4fc/src/protocol/gossip/impl/connectivity.cpp#L84), the `Stream` and `PeerContext` are deleted and than the attempt to read …

PeerContext is used after being deleted, keep shared pointer to it.

---

include/libp2p/network/impl/dialer_impl.hpp
include/libp2p/network/impl/network_impl.hpp
src/network/impl/dialer_impl.cpp
src/network/impl/network_impl.cpp
src/peer/address_repository/inmem_address_repository.cpp
test/libp2p/network/dialer_test.cpp

1. Make dialer open only one outgoing connection to a peer
2. Use sync version of conn->newStream in all cases, because the fully async one is broken and to be fixed later.
Required for kagome to speed up sync and peer discovery processes.

Fix Dialer

---

include/libp2p/crypto/ecdsa_provider.hpp
include/libp2p/crypto/ecdsa_provider/ecdsa_provider_impl.hpp
include/libp2p/crypto/ecdsa_types.hpp
src/crypto/ecdsa_provider/ecdsa_provider_impl.cpp

The change allows the dependent projects to pass messages' digests directly to the crypto provider.
Required for the [kagome](github.com/soramitsu/kagome) project.

Add interface for prehashed messages to ECDSA provider

---

src/muxer/yamux/yamuxed_connection.cpp

Fix for https://github.com/soramitsu/kagome/issues/1204.
The gist is we attempted to unconditionally dereference invalid (namely, end) iterator before reporting connection error. Now we skip this step if stream was not found.

null iterator dereferencing fix

---

src/transport/tcp/tcp_transport.cpp

TCP Connections are stored in shared ptrs and are leaking somewhere, so that when some errors happens while establishing a connection we might end up in a situation when we don't hold any references to the connection in the client code, but the socket for this connection is still open. This can easily lead to open sockets piling up to the point where the process is killed due to running out of file descriptors. This patch closes the socket on error, however the TcpConnection objects will still remain in memory, which will have to be fixed with more based refactoring.

Hotfix TCP socket leakage

---

src/muxer/yamux/yamuxed_connection.cpp

There is `if` with same condition after `assert`, so this should not `abort`.

remove assert in yamux

---

cmake/Hunter/init.cmake
include/libp2p/protocol_muxer/multiselect/common.hpp
include/libp2p/protocol_muxer/multiselect/multiselect_instance.hpp
include/libp2p/protocol_muxer/multiselect/parser.hpp
src/protocol_muxer/multiselect/multiselect_instance.cpp
src/protocol_muxer/multiselect/parser.cpp
test/libp2p/protocol_muxer/multiselect_test.cpp

Unused 'ls' command has removed in following.
Implemented following https://github.com/multiformats/go-multistream/pull/76.
Resolves issue https://github.com/soramitsu/kagome/issues/1352

Remove unused 'ls' command

---

src/security/tls/tls_details.cpp

Since we want to use version 3, we actually need to pass 2 here. I know it's confusing. Without this you will fail to interop with go-libp2p nodes since they have no idea how to parse an unknown version of x509.
Sources:
- https://github.com/openssl/openssl/blob/master/include/openssl/x509.h.in#L646
> Note: the values of these constants are defined by standards (X.509 et al) to be one less than the certificate version. So X509_VERSION_3 has value 2 and X509_VERSION_1 has value 0.
https://www.openssl.org/docs/man3.0/man3/X509_set_version.html
- Sample cert on wiki: https://en.wikipedia.org/wiki/X.509#End-entity_certificate
Note it might be better to use the defined constant `X509_VERSION_3`, but I haven't compiled the project so I knew s/3/2 was a safe change.

fix: use the correct x509 version

---

include/libp2p/injector/host_injector.hpp
include/libp2p/injector/kademlia_injector.hpp
include/libp2p/injector/network_injector.hpp

- remove unnecessary explicit singleton (to allow multiple injectors with `di::extension::shared_config`)
- use single namespace

Fix injector

---

include/libp2p/transport/tcp/tcp_util.hpp
src/transport/tcp/tcp_listener.cpp
test/libp2p/protocol_muxer/multiselect_test.cpp

Fix publishing both "/tcp" and "/tcp/ws" for same port.

tcp listener ws wss address

---

include/libp2p/basic/read.hpp
include/libp2p/basic/read_return_size.hpp
include/libp2p/layer/websocket/ssl_connection.hpp
src/layer/websocket/ssl_connection.cpp
src/layer/websocket/ws_connection.cpp
src/security/tls/tls_connection.cpp
src/transport/tcp/tcp_connection.cpp

- fix wrong read size caused by websocket empty frames
- replace `boost::asio::read` with `libp2p::read`
- `libp2p::basic::Reader::read` is deprecated and will be removed

fix ws empty frame

---

cmake/Hunter/HunterGate.cmake
include/libp2p/basic/read.hpp
include/libp2p/basic/write.hpp
include/libp2p/basic/write_queue.hpp
include/libp2p/basic/write_return_size.hpp
include/libp2p/connection/loopback_stream.hpp
include/libp2p/muxer/mplex/mplex_stream.hpp
include/libp2p/muxer/yamux/yamux_stream.hpp
include/libp2p/muxer/yamux/yamuxed_connection.hpp
include/libp2p/security/noise/noise_connection.hpp
src/basic/write_queue.cpp
src/connection/loopback_stream.cpp
src/layer/websocket/ssl_connection.cpp
src/layer/websocket/ws_connection.cpp
src/muxer/mplex/mplex_stream.cpp
src/muxer/yamux/yamux_stream.cpp
src/muxer/yamux/yamuxed_connection.cpp
src/security/noise/noise_connection.cpp
src/security/secio/secio_connection.cpp
src/security/tls/tls_connection.cpp
src/transport/tcp/tcp_connection.cpp

- Deduplicate `Reader::read`/`Writer::write` implementations with free `read`/`write` which use `Reader::readSome`/`Writer::writeSome`
- `read`/`write` success means exactly `size` bytes were read/write.
So callbacks don't need `outcome<size>`.
This prevents redundant size checks in callbacks.
Callbacks will capture buffer size if they need it.
- Fix yamux `writeSome` (can't `writeSome`/split already encoded frame with length in header)

Refactor read write some

---

include/libp2p/basic/varint_prefix_reader.hpp
src/protocol_muxer/multiselect/parser.cpp

- https://github.com/qdrvm/KAGOME-audit/issues/25
[`const MAX_LEN_BYTES: u16 = 2`](https://github.com/libp2p/rust-libp2p/blob/5ad9485bd402d0f16cb1d2b521bb4abed0938d7e/misc/multistream-select/src/length_delimited.rs#L31)

multistream max

---

.github/ISSUE_TEMPLATE/bug_report.yml
.github/ISSUE_TEMPLATE/config.yml
.github/ISSUE_TEMPLATE/enhancement.yml
.github/ISSUE_TEMPLATE/feature_request.yml

Updating the new issue templates to use the new YAML configuration system. This makes it similar to the other libp2p implementations and adds links to the technical discussions forum as well as the libp2p community discussions forum.

chore(cfg): update issue templates to new YAML system

---

CMakeLists.txt
include/libp2p/multi/multiaddress.hpp
include/libp2p/muxer/yamux/yamuxed_connection.hpp
include/libp2p/transport/impl/upgrader_session.hpp
include/libp2p/transport/tcp/tcp_connection.hpp
include/libp2p/transport/tcp/tcp_listener.hpp
include/libp2p/transport/tcp/tcp_util.hpp
include/libp2p/transport/upgrader.hpp
src/muxer/yamux/yamuxed_connection.cpp
src/transport/tcp/tcp_connection.cpp
src/transport/tcp/tcp_listener.cpp
src/transport/tcp/tcp_transport.cpp

- fix wrong observed address caused by missing `"/ws"` `"/wss"` in `TcpConnection::remoteMultiaddr()`.
- pass layers to `TcpConnection` constructor.
- fix yamux use-after-free ub.
- (#226) `std::function` or boost asio handler didn't move `Bytes`, so `BytesIn` referenced first `Bytes` which were destroyed after copying.
- callback captures `shared_ptr<Bytes> YamuxedConnection::writing_buf_` to keep `BytesIn` reference valid.

fix websocket transport

---

include/libp2p/protocol/kademlia/impl/content_routing_table.hpp
include/libp2p/protocol/kademlia/impl/content_routing_table_impl.hpp
src/protocol/kademlia/impl/content_routing_table_impl.cpp
src/protocol/kademlia/impl/kademlia_impl.cpp

- kagome tsan application_injector_test
- `ContentRoutingTableImpl` is called on init thread
- `setTimerCleanup` requires `weak_from_this`, so `io_context.post` (`scheduleWithHandle`) to libp2p thread
- libp2p thread is faster than init thread
- `setTimerCleanup` is called, calls `weak_from_this`
- but init thread is still inside `make_shared` and didn't initialize `enable_shared_from_this`
- `ContentRoutingTableImpl::start` is called by `KademliaImpl::start` (so user doesn't need to call it)

tsan weak_from_this race

---

README.md

Changed `hunter.sh` which doesn't exist in the project structure and when typed into the browser is a hijacked domain. It now points to the github page for the Hunter project specifically used in the build workflow. PRs goal is to resolve #250

Corrected Hunter link in README

---

include/libp2p/security/tls/tls_errors.hpp
src/security/tls/tls_adaptor.cpp
src/security/tls/tls_connection.cpp
src/security/tls/tls_connection.hpp
src/security/tls/tls_details.cpp

- Remove `dynamic_cast`.
- Can use TLS over any libp2p stream.
- Can use in WASM (browsers don't allow TCP).

Remove TLS dependency on TCP

---

include/libp2p/host/basic_host/basic_host.hpp
include/libp2p/host/host.hpp
include/libp2p/injector/host_injector.hpp
src/host/basic_host/basic_host.cpp
test/acceptance/p2p/host/basic_host_test.cpp
test/acceptance/p2p/host/peer/test_peer.cpp

Make identify agent version configurable

Identify agent version

---

include/libp2p/protocol/kademlia/impl/get_value_executor.hpp
src/protocol/kademlia/impl/get_value_executor.cpp

- insufficient quorum is not an error
```
polkadot-sdk/substrate/client/network/src/discovery.rs:
96: // The minimum number of peers we expect an answer before we terminate the request.
97: const GET_RECORD_REDUNDANCY_FACTOR: u32 = 4;
889:     Ok(GetRecordOk::FoundRecord(r)) => {
899:       // Let's directly finish the query if we are above 4.
905:       if stats.num_successes() > GET_RECORD_REDUNDANCY_FACTOR {
908:         query.finish();
917:       DiscoveryOut::ValueFound(r, stats.duration().unwrap_or_default())
919:     Ok(GetRecordOk::FinishedWithNoAdditionalRecord {
```

fix kad quorum

---

include/libp2p/muxer/yamux/yamuxed_connection.hpp
src/muxer/yamux/yamuxed_connection.cpp

- close underlying connection after sending pending messages
- fix (wrong if) send go away message

yamux close underlying connection

---

include/libp2p/protocol/kademlia/impl/kademlia_impl.hpp
include/libp2p/protocol/kademlia/impl/session.hpp
include/libp2p/protocol/kademlia/impl/session_host.hpp
include/libp2p/protocol/kademlia/message.hpp
src/protocol/kademlia/impl/add_provider_executor.cpp
src/protocol/kademlia/impl/find_peer_executor.cpp
src/protocol/kademlia/impl/find_providers_executor.cpp
src/protocol/kademlia/impl/get_value_executor.cpp
src/protocol/kademlia/impl/kademlia_impl.cpp
src/protocol/kademlia/impl/put_value_executor.cpp
src/protocol/kademlia/impl/session.cpp
src/protocol/kademlia/message.cpp

- `read` was called twice, from `onMessageRead` and `onMessageWritten`
- simplify and deduplicate read/write request/response
- server (`SessionHost`) reads request, writes response, repeats.
- client (`ResponseHandler`) writes request, reads response, closes stream.
- `ADD_PROVIDER` writes request, (no response), closes stream.
- `read` uses `MessageReadWriterUvarint`, but `write` doesn't use that because `Message::serialize` adds length prefix.

fix kad double read

---

src/network/impl/connection_manager_impl.cpp

Don't return closed connections from `getConnections` and `getConnectionsToPeer` to be consistent with `getBestConnectionForPeer`

fix getConnections

---

include/libp2p/muxer/yamux/yamux_stream.hpp
src/muxer/yamux/yamux_stream.cpp
src/muxer/yamux/yamuxed_connection.cpp
src/transport/tcp/tcp_connection.cpp

`YamuxStream::readSome` callback was not called.
Also removed some related checks preventing callbacks from being called.

fix yamux callback

---

include/libp2p/multi/multiaddress_protocol_list.hpp

I am preparing this implementation to be distributed as a Debian package. It requires running all the available tests despite the `Debug` or `Release` build type being selected for CMake. The presence of `NDEBUG` definition tracking in the code removes this possibility because the absence of the `_DUMMY_PROTO_` section in `multiaddress_protocol_list.h` allows successful compilation only when the tests are not compiled. Otherwise, the following error occurs:
```
/home/twdragon/src/libp2p-cpp/test/libp2p/transport/upgrader_test.cpp:76:38: error: no member named '_DUMMY_PROTO_1' in 'libp2p::multi::Protocol::Code'
libp2p::multi::Protocol::Code::_DUMMY_PROTO_1,
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^
/home/twdragon/src/libp2p-cpp/test/libp2p/transport/upgrader_test.cpp:77:38: error: no member named …
```

Removed NDEBUG tracking for compiling tests in Release mode

---

src/muxer/yamux/yamuxed_connection.cpp

We obtained the following core dump during KAGOME testing (that uses cpp-libp2p):
[gdb.txt](https://github.com/user-attachments/files/19428624/gdb.txt)
In particular we see:
```cpp
#8  0x000055e7e280a972 in libp2p::connection::YamuxedConnection::~YamuxedConnection() ()
...
#11 0x000055e7e281005d in libp2p::connection::YamuxedConnection::close(std::error_code, boost::optional<libp2p::connection::YamuxFrame::GoAwayError>) ()
```
which is the evidence that `YamuxedConnection` was destroyed during `close` method invocation.
This could potentially happen if during
```cpp
closed_callback_(remote_peer_, shared_from_this());
```
destruction of current `YamuxedConnection` was triggered and therefore second attempt to destroy `YamuxedConnection` lead to double free.
As a workaround it is proposed …

Fix close YamuxedConnection

---

include/libp2p/protocol_muxer/multiselect.hpp
include/libp2p/protocol_muxer/multiselect/multiselect_instance.hpp
src/protocol_muxer/multiselect.cpp
src/protocol_muxer/multiselect/multiselect_instance.cpp
test/acceptance/p2p/host/peer/test_peer.cpp

Adds timeout on MultiselectInstance's selectOneOf

feat: add scheduler support for timeout management in Multiselect
